# jruby -S gem install jdbc-h2 --no-ri --no-rdoc
# jruby -S gem install activerecord-jdbc-adapter --no-ri --no-rdoc
# jruby -S gem install activerecord-jdbch2-adapter --no-ri --no-rdoc
#jruby -S gem install warbler --source http://caldersphere.net

development:
  adapter: jdbch2
  database: <%= RAILS_ROOT %>/db/gsn_h2_database

production:
  adapter: jdbch2
  database: <%= RAILS_ROOT %>/db/gsn_h2_database