# jruby -S gem install jdbc-h2 --no-ri --no-rdoc
# jruby -S gem install activerecord-jdbc-adapter --no-ri --no-rdoc
# jruby -S gem install activerecord-jdbch2-adapter --no-ri --no-rdoc
# jruby -S gem install warbler --source http://caldersphere.net

# Migrate the database with
# jruby -S rake db:migrate

development:
  adapter: jdbch2
  database: <%= RAILS_ROOT %>/db/gsn_h2_database
  #adapter: mysql
  #database: gsn
  #username: root
  #password:
  #host: 127.0.0.1

production:
  adapter: jdbch2
  database: <%= RAILS_ROOT %>/db/gsn_h2_database
  #adapter: mysql
  #database: gsn
  #username: root
  #password:
  #host: 127.0.0.1